name: Release
on:
  create:
    tags:
    - v*
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: aliyun-oss-website-action
          # You may pin to the exact commit or the version.
          # uses: fangbinwei/aliyun-oss-website-action@83a47e5e40b4185c8d221148bd314bb57015d7e4
          uses: fangbinwei/aliyun-oss-website-action@v1.4.1
          with:
            # Folder which contains the website files
            folder: "cn"
            # Aliyun OSS accessKeyId.
            accessKeyId: ${{secrets.ACCESS_KEY}}
            # Aliyun OSS accessKeySecret.
            accessKeySecret: ${{secrets.ACCESS_SECRET}}
            # Aliyun OSS bucket instance.
            bucket: ${{secrets.BUCKET}}
            # OSS region domain
            endpoint: ${{secrets.ENDPOINT}}
            # `true` to identify the endpoint is your custom domain.
            cname: ${{secrets.CNAME}}
          
