- name: ali-oss-uploader
  # You may pin to the exact commit or the version.
  # uses: leftsky/ali-oss-upload-action@48c9cabd728375d5203473ede77f4a9f6f12748f
  uses: leftsky/ali-oss-upload-action@v1.0.1
  with:
    # 阿里云OSS地域
    region: # optional
    # 阿里云OSS Endpoint
    endpoint: # optional
    # 阿里云OSS AccessKeyId
    key-id: 
    # 阿里云OSS AccessKeySecret
    key-secret: 
    # 阿里云OSS Bucket
    bucket: 
    # 需要上传的文件或文件夹
    dir: 
    # 上传到OSS的目标文件夹
    target-dir: 
          
